spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  type-aliases-package: com.sicnu.zhaiyue.mapper
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  mapper-location: classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8282

myport: ${server.port}